language: go
go:
- 1.9.x
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Blevesearch Site Auto Publisher"
  - GIT_EMAIL="mschoch@users.noreply.github.com"
before_install:
- openssl aes-256-cbc -K $encrypted_4373be943248_key -iv $encrypted_4373be943248_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- go get github.com/blevesearch/hugoidx
- go get github.com/blevesearch/blevex/preload/...
#- go get google.golang.org/appengine/cmd/aedeploy
#- go get -u github.com/FiloSottile/gvt
before_script:
- curl -sLO https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_linux_amd64.tar.gz
- tar zxvf hugo_0.14_linux_amd64.tar.gz
script:
- export REV=$(git rev-parse HEAD)
- chmod 600 $SSH_KEY
- eval `ssh-agent -s`
- ssh-add $SSH_KEY
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git clone git@github.com:blevesearch/blevesearch.github.io.git public
- hugo_0.14_linux_amd64/hugo_0.14_linux_amd64 -s .
after_success:
- cd public
- git add -A .
- git commit --allow-empty -m "Built from commit $REV"
- git push origin master
- cd ..
- hugoidx
- bleve_export search.bleve search.blexport
- git clone https://github.com/blevesearch/bleve-hosted.git
- rm -rf bleve-hosted/indexes/test.bleve
- cp search.blexport bleve-hosted/indexes/search.bleve
- go get -u -v github.com/gorilla/mux
- cd bleve-hosted
# TODO: Deploying search.bleve
# - curl -sLO https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip
# - unzip -q go_appengine_sdk_linux_amd64-1.9.40.zip
# - ../go_appengine/appcfg.py --oauth2_refresh_token=$GAE_OAUTH update -A bleve-search -V $REV .
# - ../go_appengine/appcfg.py --oauth2_refresh_token=$GAE_OAUTH set_default_version -A bleve-search -V $REV
# - curl -sLO https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
# - tar zxvf google-cloud-sdk.tar.gz
# - touch /home/travis/.bashrc
# - google-cloud-sdk/install.sh --usage-reporting false --path-update true --rc-path=/home/travis/.bashrc --bash-completion true
# - source google-cloud-sdk/path.bash.inc
# - gcloud components update preview app --quiet
# - gcloud auth activate-service-account --key-file gae_secret.json
# - cd bleve-hosted
# - gvt fetch github.com/blevesearch/bleve
# - ls -l vendor
# - go get -v .
# - go get github.com/gorilla/context
# - go get github.com/blevesearch/bleve/analysis
# - go get github.com/blevesearch/bleve/registry
# - go get github.com/blevesearch/bleve/document
#- ls -l /home/travis/gopath/src/github.com/blevesearch/bleve/analysis
# - gcloud config set project bleve-search
# - gcloud app deploy --quiet
